specVersion: 1.0.0
name: autonomy-astroport-mainnet-subquery
version: 0.0.1
runner:
  node:
    name: "@subql/node-terra"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  This project can be use as a starting point for developing your
  Terra based SubQuery project
repository: https://github.com/subquery/juno-subql-starter
schema:
  file: ./schema.graphql

network:
  chainId: phoenix-1
  # This endpoint must be a public non-pruned archive node
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  # You can get them from OnFinality for free https://app.onfinality.io
  # https://documentation.onfinality.io/support/the-enhanced-api-service
  endpoint: ec2-3-1-101-36.ap-southeast-1.compute.amazonaws.com:1317
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  # dictionary: https://api.subquery.network/sq/subquery/terra-juno-dictionary


dataSources:
  - kind: terra/Runtime
    startBlock: 2904752
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleCreateRequestEvent
          kind: terra/EventHandler
          filter:
            type: wasm
            attributes:
              _contract_address: "terra1za5a509w6jvahlcwepnyfzxlwd3wm4lvpmua4w32ypn2we3gjajq5hfkdv"
              action: "create_request"
        - handler: handleExecuteRequestEvent
          kind: terra/EventHandler
          filter:
            type: wasm
            attributes:
              _contract_address: "terra1za5a509w6jvahlcwepnyfzxlwd3wm4lvpmua4w32ypn2we3gjajq5hfkdv"
              action: "execute_request"
        - handler: handleCancelRequestEvent
          kind: terra/EventHandler
          filter:
            type: wasm
            attributes:
              _contract_address: "terra1za5a509w6jvahlcwepnyfzxlwd3wm4lvpmua4w32ypn2we3gjajq5hfkdv"
              action: "cancel_request"